builds:
- env:
  - CGO_ENABLED=0
  binary: fleet
  goarch:
  - arm
  - arm64
  - amd64
  goos:
  - windows
  - darwin
  - linux
archives:
- name_template: "fleet_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - 'Merge pull request'
release:
  prerelease: auto
