apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-operator
spec:
  selector:
    matchLabels:
      app: k3s-operator
  template:
    metadata:
      labels:
        app: k3s-operator
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: k3s-operator
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
      serviceAccountName: k3s-operator
