apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k3s-operator
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - "k3s.ibtc.io"
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k3s-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k3s-operator
subjects:
- kind: ServiceAccount
  name: k3s-operator
  namespace: {{.Release.Namespace}}
