apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: k3ses.k3s.ibtc.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.ready
    name: Ready
    type: string
  - JSONPath: .status.clientSecretName
    name: Kubeconfig
    type: string
  group: k3s.ibtc.io
  names:
    kind: K3s
    plural: k3ses
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            channel:
              nullable: true
              type: string
            controlPlaneEndpoint:
              nullable: true
              properties:
                host:
                  nullable: true
                  type: string
                port:
                  type: integer
              type: object
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    nullable: true
                    type: string
                  lastUpdateTime:
                    nullable: true
                    type: string
                  message:
                    nullable: true
                    type: string
                  reason:
                    nullable: true
                    type: string
                  status:
                    nullable: true
                    type: string
                  type:
                    nullable: true
                    type: string
                type: object
              nullable: true
              type: array
            credentialSecretName:
              nullable: true
              type: string
            observedGeneration:
              type: integer
            ready:
              type: boolean
            token:
              nullable: true
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
